### PR TITLE
he's a css wizard, there has to be a trick

### PR DESCRIPTION
**Pull request by phever**
hopefully this is what you're looking for with the images, this at least makes normal sized monitors a lot more readable

### CODE REVIEW

**Comment by dylanlan** [comment]
Thank you for the incantation, o' CSS wizard! Alas, it seems something might've went wrong with the spell - for the layout still appears the same for me, on Windows 10 & Chrome. I have even tried clearing my cache, but that didn't seem to help.

Please let me know if I am missing something - I feel like I am still trying to learn beag css some days.

Here are some screenshots for reference:

Adventure Log:

production

with-css

Cursed Mail:

mail-production

mail-mike

My first goal is to make the Cursed mail letters more readable, since they're currently a bit smooshed, and hard to read. I also want to use more of the horizontal space for the other images and text, if possible. So much wasted whitespace makes me feel bad, but I also don't think I want ginormous screenshots, so a healthy balance would be lovely.

I had commented out some `max-width: 60rem;` in the `.content` css, which _seemed_ to be close to what I wanted. I think I was seeing some undesired text lengths elsewhere, or something - I haven't had time to take a second look yet. But maybe it's good enough to iterate on. For reference:

max-width-rem

Let me know if you have any other information or css spells!

**Comment by phever** [comment]
That tiny CSS patch should give you exactly the functionality you're looking for. It was working on my local copy. I'll double check

**Comment by phever** [comment]
20240115_12h54m30s_grim

**Comment by dylanlan** [comment]
Ok, sorry for the confusion - thanks!! ❤️

**Pull request merged**
